# Generated by Django 3.0.4 on 2020-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200401_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='console',
            field=models.ManyToManyField(to='main_app.Console'),
        ),
    ]
