# Generated by Django 3.0.4 on 2020-04-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_game_console'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='console',
            new_name='consoles',
        ),
    ]
