# Generated by Django 3.0.4 on 2020-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200401_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='playTime',
            field=models.CharField(choices=[('1', '0-4'), ('2', '4-6'), ('3', '6+')], default='1', max_length=1),
        ),
    ]
